services:
  app:
    build:
      dockerfile: ./Dockerfile
    container_name: django_app
    command:
      - "gunicorn"
      - "mysite.wsgi:application"
      - "--bind"
      - "0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - ./mysite/database:/app/database
      - ./staticfiles:/app/staticfiles # Монтируем статику
    env_file:
      - .env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80" # Открываем порт 80 наружу
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/var/www/staticfiles:ro # Nginx будет отдавать статику отсюда
    depends_on:
      - app
    restart: always