# Generated by Django 5.2.5 on 2025-09-02 09:33

from shopapp.models import product_preview_directory_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=product_preview_directory_path),
        ),
    ]
