# Generated by Django 5.2.5 on 2025-09-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
